[   {   'guidislink': False,
        'id': u'http://timesofindia.indiatimes.com/elections/assembly-elections/uttar-pradesh/news/opposition-believes-in-kuch-ka-saath-kuch-ka-vikas-says-pm-modi-in-varanasi/articleshow/57480913.cms',
        'link': u'http://timesofindia.indiatimes.com/elections/assembly-elections/uttar-pradesh/news/opposition-believes-in-kuch-ka-saath-kuch-ka-vikas-says-pm-modi-in-varanasi/articleshow/57480913.cms',
        'links': [   {   'href': u'http://timesofindia.indiatimes.com/elections/assembly-elections/uttar-pradesh/news/opposition-believes-in-kuch-ka-saath-kuch-ka-vikas-says-pm-modi-in-varanasi/articleshow/57480913.cms',
                         'rel': u'alternate',
                         'type': u'text/html'}],
        'published': u'Sun, 05 Mar 2017 15:22:17 GMT',
        'published_parsed': time.struct_time(tm_year=2017, tm_mon=3, tm_mday=5, tm_hour=15, tm_min=22, tm_sec=17, tm_wday=6, tm_yday=64, tm_isdst=0),
        'summary': u'"I have big dreams for Varanasi, but the SP-led state government is putting roadblocks in the implementation of development programmes," Prime Minister Narendra Modi said addressing a rally in Varanasi.',
        'summary_detail': {   'base': u'http://timesofindia.indiatimes.com/rssfeedstopstories.cms',
                              'language': u'en-US',
                              'type': u'text/html',
                              'value': u'"I have big dreams for Varanasi, but the SP-led state government is putting roadblocks in the implementation of development programmes," Prime Minister Narendra Modi said addressing a rally in Varanasi.'},
        'title': u"Oppn believes in 'kuch ka saath, kuch ka vikas', says PM Modi in Varanasi",
        'title_detail': {   'base': u'http://timesofindia.indiatimes.com/rssfeedstopstories.cms',
                            'language': u'en-US',
                            'type': u'text/plain',
                            'value': u"Oppn believes in 'kuch ka saath, kuch ka vikas', says PM Modi in Varanasi"}},
    {   'guidislink': False,
        'id': u'http://timesofindia.indiatimes.com/elections/assembly-elections/uttar-pradesh/news/pm-modis-roadshow-in-varanasi-bjp-upbeat-campaign-will-fail-says-akhilesh-yadav/articleshow/57479778.cms',
        'link': u'http://timesofindia.indiatimes.com/elections/assembly-elections/uttar-pradesh/news/pm-modis-roadshow-in-varanasi-bjp-upbeat-campaign-will-fail-says-akhilesh-yadav/articleshow/57479778.cms',
        'links': [   {   'href': u'http://timesofindia.indiatimes.com/elections/assembly-elections/uttar-pradesh/news/pm-modis-roadshow-in-varanasi-bjp-upbeat-campaign-will-fail-says-akhilesh-yadav/articleshow/57479778.cms',
                         'rel': u'alternate',
                         'type': u'text/html'}],
        'published': u'Sun, 05 Mar 2017 14:00:53 GMT',
        'published_parsed': time.struct_time(tm_year=2017, tm_mon=3, tm_mday=5, tm_hour=14, tm_min=0, tm_sec=53, tm_wday=6, tm_yday=64, tm_isdst=0),
        'summary': u'Large number of BJP supporters descended on the streets of Varanasi on Sunday as Prime Minister Narendra Modi held a roadshow in the city, the second in as many days. Varanasi goes to polls in the last phase on March 8.',
        'summary_detail': {   'base': u'http://timesofindia.indiatimes.com/rssfeedstopstories.cms',
                              'language': u'en-US',
                              'type': u'text/html',
                              'value': u'Large number of BJP supporters descended on the streets of Varanasi on Sunday as Prime Minister Narendra Modi held a roadshow in the city, the second in as many days. Varanasi goes to polls in the last phase on March 8.'},
        'title': u"PM Modi's roadshow will fail, says Akhilesh",
        'title_detail': {   'base': u'http://timesofindia.indiatimes.com/rssfeedstopstories.cms',
                            'language': u'en-US',
                            'type': u'text/plain',
                            'value': u"PM Modi's roadshow will fail, says Akhilesh"}},
    {   'guidislink': False,
        'id': u'http://timesofindia.indiatimes.com/sports/cricket/australia-in-india/india-v-australia-renshaw-laughs-off-kohlis-toilet-sledge/articleshow/57480238.cms',
        'link': u'http://timesofindia.indiatimes.com/sports/cricket/australia-in-india/india-v-australia-renshaw-laughs-off-kohlis-toilet-sledge/articleshow/57480238.cms',
        'links': [   {   'href': u'http://timesofindia.indiatimes.com/sports/cricket/australia-in-india/india-v-australia-renshaw-laughs-off-kohlis-toilet-sledge/articleshow/57480238.cms',
                         'rel': u'alternate',
                         'type': u'text/html'}],
        'published': u'Sun, 05 Mar 2017 14:22:59 GMT',
        'published_parsed': time.struct_time(tm_year=2017, tm_mon=3, tm_mday=5, tm_hour=14, tm_min=22, tm_sec=59, tm_wday=6, tm_yday=64, tm_isdst=0),
        'summary': u'Young Australian opener Matt Renshaw has belied his age with the way he has batted so far on the tour of India and on Sunday, he was equally impressive in negotiating the constant sledging from Virat Kohli.',
        'summary_detail': {   'base': u'http://timesofindia.indiatimes.com/rssfeedstopstories.cms',
                              'language': u'en-US',
                              'type': u'text/html',
                              'value': u'Young Australian opener Matt Renshaw has belied his age with the way he has batted so far on the tour of India and on Sunday, he was equally impressive in negotiating the constant sledging from Virat Kohli.'},
        'title': u"Renshaw laughs off Kohli's 'toilet' sledge",
        'title_detail': {   'base': u'http://timesofindia.indiatimes.com/rssfeedstopstories.cms',
                            'language': u'en-US',
                            'type': u'text/plain',
                            'value': u"Renshaw laughs off Kohli's 'toilet' sledge"}},
    {   'guidislink': False,
        'id': u'http://timesofindia.indiatimes.com/india/up-governor-writes-to-akhilesh-yadav-why-is-rape-accused-minister-still-in-your-cabinet/articleshow/57477674.cms',
        'link': u'http://timesofindia.indiatimes.com/india/up-governor-writes-to-akhilesh-yadav-why-is-rape-accused-minister-still-in-your-cabinet/articleshow/57477674.cms',
        'links': [   {   'href': u'http://timesofindia.indiatimes.com/india/up-governor-writes-to-akhilesh-yadav-why-is-rape-accused-minister-still-in-your-cabinet/articleshow/57477674.cms',
                         'rel': u'alternate',
                         'type': u'text/html'}],
        'published': u'Sun, 05 Mar 2017 10:45:31 GMT',
        'published_parsed': time.struct_time(tm_year=2017, tm_mon=3, tm_mday=5, tm_hour=10, tm_min=45, tm_sec=31, tm_wday=6, tm_yday=64, tm_isdst=0),
        'summary': u'Uttar Pradesh Governor Ram Naik has written to Akhilesh Yadav asking why has the chief minister retained rape-accused minister Gayatri Prajapati in his cabinet, according to Raj Bhavan sources.',
        'summary_detail': {   'base': u'http://timesofindia.indiatimes.com/rssfeedstopstories.cms',
                              'language': u'en-US',
                              'type': u'text/html',
                              'value': u'Uttar Pradesh Governor Ram Naik has written to Akhilesh Yadav asking why has the chief minister retained rape-accused minister Gayatri Prajapati in his cabinet, according to Raj Bhavan sources.'},
        'title': u'Why rape-accused in cabinet? UP Governor to CM',
        'title_detail': {   'base': u'http://timesofindia.indiatimes.com/rssfeedstopstories.cms',
                            'language': u'en-US',
                            'type': u'text/plain',
                            'value': u'Why rape-accused in cabinet? UP Governor to CM'}},
    {   'guidislink': False,
        'id': u'http://timesofindia.indiatimes.com/world/us/white-house-asks-congress-to-probe-whether-obama-ordered-wiretap/articleshow/57480314.cms',
        'link': u'http://timesofindia.indiatimes.com/world/us/white-house-asks-congress-to-probe-whether-obama-ordered-wiretap/articleshow/57480314.cms',
        'links': [   {   'href': u'http://timesofindia.indiatimes.com/world/us/white-house-asks-congress-to-probe-whether-obama-ordered-wiretap/articleshow/57480314.cms',
                         'rel': u'alternate',
                         'type': u'text/html'}],
        'published': u'Sun, 05 Mar 2017 14:30:04 GMT',
        'published_parsed': time.struct_time(tm_year=2017, tm_mon=3, tm_mday=5, tm_hour=14, tm_min=30, tm_sec=4, tm_wday=6, tm_yday=64, tm_isdst=0),
        'summary': u'The White House on Sunday requested the US Congress examine whether the Obama administration abused its executive "investigative authority" during the 2016 campaign, as part of the ongoing congressional probe into Russia\'s influence on the US presidential election.',
        'summary_detail': {   'base': u'http://timesofindia.indiatimes.com/rssfeedstopstories.cms',
                              'language': u'en-US',
                              'type': u'text/html',
                              'value': u'The White House on Sunday requested the US Congress examine whether the Obama administration abused its executive "investigative authority" during the 2016 campaign, as part of the ongoing congressional probe into Russia\'s influence on the US presidential election.'},
        'title': u'Did Obama order wiretap? Trump seeks probe',
        'title_detail': {   'base': u'http://timesofindia.indiatimes.com/rssfeedstopstories.cms',
                            'language': u'en-US',
                            'type': u'text/plain',
                            'value': u'Did Obama order wiretap? Trump seeks probe'}}][   {   'guidislink': False,
        'id': u'http://timesofindia.indiatimes.com/elections/assembly-elections/uttar-pradesh/news/opposition-believes-in-kuch-ka-saath-kuch-ka-vikas-says-pm-modi-in-varanasi/articleshow/57480913.cms',
        'link': u'http://timesofindia.indiatimes.com/elections/assembly-elections/uttar-pradesh/news/opposition-believes-in-kuch-ka-saath-kuch-ka-vikas-says-pm-modi-in-varanasi/articleshow/57480913.cms',
        'links': [   {   'href': u'http://timesofindia.indiatimes.com/elections/assembly-elections/uttar-pradesh/news/opposition-believes-in-kuch-ka-saath-kuch-ka-vikas-says-pm-modi-in-varanasi/articleshow/57480913.cms',
                         'rel': u'alternate',
                         'type': u'text/html'}],
        'published': u'Sun, 05 Mar 2017 15:22:17 GMT',
        'published_parsed': time.struct_time(tm_year=2017, tm_mon=3, tm_mday=5, tm_hour=15, tm_min=22, tm_sec=17, tm_wday=6, tm_yday=64, tm_isdst=0),
        'summary': u'"I have big dreams for Varanasi, but the SP-led state government is putting roadblocks in the implementation of development programmes," Prime Minister Narendra Modi said addressing a rally in Varanasi.',
        'summary_detail': {   'base': u'http://timesofindia.indiatimes.com/rssfeedstopstories.cms',
                              'language': u'en-US',
                              'type': u'text/html',
                              'value': u'"I have big dreams for Varanasi, but the SP-led state government is putting roadblocks in the implementation of development programmes," Prime Minister Narendra Modi said addressing a rally in Varanasi.'},
        'title': u"Oppn believes in 'kuch ka saath, kuch ka vikas', says PM Modi in Varanasi",
        'title_detail': {   'base': u'http://timesofindia.indiatimes.com/rssfeedstopstories.cms',
                            'language': u'en-US',
                            'type': u'text/plain',
                            'value': u"Oppn believes in 'kuch ka saath, kuch ka vikas', says PM Modi in Varanasi"}},
    {   'guidislink': False,
        'id': u'http://timesofindia.indiatimes.com/elections/assembly-elections/uttar-pradesh/news/pm-modis-roadshow-in-varanasi-bjp-upbeat-campaign-will-fail-says-akhilesh-yadav/articleshow/57479778.cms',
        'link': u'http://timesofindia.indiatimes.com/elections/assembly-elections/uttar-pradesh/news/pm-modis-roadshow-in-varanasi-bjp-upbeat-campaign-will-fail-says-akhilesh-yadav/articleshow/57479778.cms',
        'links': [   {   'href': u'http://timesofindia.indiatimes.com/elections/assembly-elections/uttar-pradesh/news/pm-modis-roadshow-in-varanasi-bjp-upbeat-campaign-will-fail-says-akhilesh-yadav/articleshow/57479778.cms',
                         'rel': u'alternate',
                         'type': u'text/html'}],
        'published': u'Sun, 05 Mar 2017 14:00:53 GMT',
        'published_parsed': time.struct_time(tm_year=2017, tm_mon=3, tm_mday=5, tm_hour=14, tm_min=0, tm_sec=53, tm_wday=6, tm_yday=64, tm_isdst=0),
        'summary': u'Large number of BJP supporters descended on the streets of Varanasi on Sunday as Prime Minister Narendra Modi held a roadshow in the city, the second in as many days. Varanasi goes to polls in the last phase on March 8.',
        'summary_detail': {   'base': u'http://timesofindia.indiatimes.com/rssfeedstopstories.cms',
                              'language': u'en-US',
                              'type': u'text/html',
                              'value': u'Large number of BJP supporters descended on the streets of Varanasi on Sunday as Prime Minister Narendra Modi held a roadshow in the city, the second in as many days. Varanasi goes to polls in the last phase on March 8.'},
        'title': u"PM Modi's roadshow will fail, says Akhilesh",
        'title_detail': {   'base': u'http://timesofindia.indiatimes.com/rssfeedstopstories.cms',
                            'language': u'en-US',
                            'type': u'text/plain',
                            'value': u"PM Modi's roadshow will fail, says Akhilesh"}},
    {   'guidislink': False,
        'id': u'http://timesofindia.indiatimes.com/sports/cricket/australia-in-india/india-v-australia-renshaw-laughs-off-kohlis-toilet-sledge/articleshow/57480238.cms',
        'link': u'http://timesofindia.indiatimes.com/sports/cricket/australia-in-india/india-v-australia-renshaw-laughs-off-kohlis-toilet-sledge/articleshow/57480238.cms',
        'links': [   {   'href': u'http://timesofindia.indiatimes.com/sports/cricket/australia-in-india/india-v-australia-renshaw-laughs-off-kohlis-toilet-sledge/articleshow/57480238.cms',
                         'rel': u'alternate',
                         'type': u'text/html'}],
        'published': u'Sun, 05 Mar 2017 14:22:59 GMT',
        'published_parsed': time.struct_time(tm_year=2017, tm_mon=3, tm_mday=5, tm_hour=14, tm_min=22, tm_sec=59, tm_wday=6, tm_yday=64, tm_isdst=0),
        'summary': u'Young Australian opener Matt Renshaw has belied his age with the way he has batted so far on the tour of India and on Sunday, he was equally impressive in negotiating the constant sledging from Virat Kohli.',
        'summary_detail': {   'base': u'http://timesofindia.indiatimes.com/rssfeedstopstories.cms',
                              'language': u'en-US',
                              'type': u'text/html',
                              'value': u'Young Australian opener Matt Renshaw has belied his age with the way he has batted so far on the tour of India and on Sunday, he was equally impressive in negotiating the constant sledging from Virat Kohli.'},
        'title': u"Renshaw laughs off Kohli's 'toilet' sledge",
        'title_detail': {   'base': u'http://timesofindia.indiatimes.com/rssfeedstopstories.cms',
                            'language': u'en-US',
                            'type': u'text/plain',
                            'value': u"Renshaw laughs off Kohli's 'toilet' sledge"}},
    {   'guidislink': False,
        'id': u'http://timesofindia.indiatimes.com/india/up-governor-writes-to-akhilesh-yadav-why-is-rape-accused-minister-still-in-your-cabinet/articleshow/57477674.cms',
        'link': u'http://timesofindia.indiatimes.com/india/up-governor-writes-to-akhilesh-yadav-why-is-rape-accused-minister-still-in-your-cabinet/articleshow/57477674.cms',
        'links': [   {   'href': u'http://timesofindia.indiatimes.com/india/up-governor-writes-to-akhilesh-yadav-why-is-rape-accused-minister-still-in-your-cabinet/articleshow/57477674.cms',
                         'rel': u'alternate',
                         'type': u'text/html'}],
        'published': u'Sun, 05 Mar 2017 10:45:31 GMT',
        'published_parsed': time.struct_time(tm_year=2017, tm_mon=3, tm_mday=5, tm_hour=10, tm_min=45, tm_sec=31, tm_wday=6, tm_yday=64, tm_isdst=0),
        'summary': u'Uttar Pradesh Governor Ram Naik has written to Akhilesh Yadav asking why has the chief minister retained rape-accused minister Gayatri Prajapati in his cabinet, according to Raj Bhavan sources.',
        'summary_detail': {   'base': u'http://timesofindia.indiatimes.com/rssfeedstopstories.cms',
                              'language': u'en-US',
                              'type': u'text/html',
                              'value': u'Uttar Pradesh Governor Ram Naik has written to Akhilesh Yadav asking why has the chief minister retained rape-accused minister Gayatri Prajapati in his cabinet, according to Raj Bhavan sources.'},
        'title': u'Why rape-accused in cabinet? UP Governor to CM',
        'title_detail': {   'base': u'http://timesofindia.indiatimes.com/rssfeedstopstories.cms',
                            'language': u'en-US',
                            'type': u'text/plain',
                            'value': u'Why rape-accused in cabinet? UP Governor to CM'}},
    {   'guidislink': False,
        'id': u'http://timesofindia.indiatimes.com/world/us/white-house-asks-congress-to-probe-whether-obama-ordered-wiretap/articleshow/57480314.cms',
        'link': u'http://timesofindia.indiatimes.com/world/us/white-house-asks-congress-to-probe-whether-obama-ordered-wiretap/articleshow/57480314.cms',
        'links': [   {   'href': u'http://timesofindia.indiatimes.com/world/us/white-house-asks-congress-to-probe-whether-obama-ordered-wiretap/articleshow/57480314.cms',
                         'rel': u'alternate',
                         'type': u'text/html'}],
        'published': u'Sun, 05 Mar 2017 14:30:04 GMT',
        'published_parsed': time.struct_time(tm_year=2017, tm_mon=3, tm_mday=5, tm_hour=14, tm_min=30, tm_sec=4, tm_wday=6, tm_yday=64, tm_isdst=0),
        'summary': u'The White House on Sunday requested the US Congress examine whether the Obama administration abused its executive "investigative authority" during the 2016 campaign, as part of the ongoing congressional probe into Russia\'s influence on the US presidential election.',
        'summary_detail': {   'base': u'http://timesofindia.indiatimes.com/rssfeedstopstories.cms',
                              'language': u'en-US',
                              'type': u'text/html',
                              'value': u'The White House on Sunday requested the US Congress examine whether the Obama administration abused its executive "investigative authority" during the 2016 campaign, as part of the ongoing congressional probe into Russia\'s influence on the US presidential election.'},
        'title': u'Did Obama order wiretap? Trump seeks probe',
        'title_detail': {   'base': u'http://timesofindia.indiatimes.com/rssfeedstopstories.cms',
                            'language': u'en-US',
                            'type': u'text/plain',
                            'value': u'Did Obama order wiretap? Trump seeks probe'}}][   {   'guidislink': False,
        'id': u'http://timesofindia.indiatimes.com/elections/assembly-elections/uttar-pradesh/news/opposition-believes-in-kuch-ka-saath-kuch-ka-vikas-says-pm-modi-in-varanasi/articleshow/57480913.cms',
        'link': u'http://timesofindia.indiatimes.com/elections/assembly-elections/uttar-pradesh/news/opposition-believes-in-kuch-ka-saath-kuch-ka-vikas-says-pm-modi-in-varanasi/articleshow/57480913.cms',
        'links': [   {   'href': u'http://timesofindia.indiatimes.com/elections/assembly-elections/uttar-pradesh/news/opposition-believes-in-kuch-ka-saath-kuch-ka-vikas-says-pm-modi-in-varanasi/articleshow/57480913.cms',
                         'rel': u'alternate',
                         'type': u'text/html'}],
        'published': u'Sun, 05 Mar 2017 15:22:17 GMT',
        'published_parsed': time.struct_time(tm_year=2017, tm_mon=3, tm_mday=5, tm_hour=15, tm_min=22, tm_sec=17, tm_wday=6, tm_yday=64, tm_isdst=0),
        'summary': u'"I have big dreams for Varanasi, but the SP-led state government is putting roadblocks in the implementation of development programmes," Prime Minister Narendra Modi said addressing a rally in Varanasi.',
        'summary_detail': {   'base': u'http://timesofindia.indiatimes.com/rssfeedstopstories.cms',
                              'language': u'en-US',
                              'type': u'text/html',
                              'value': u'"I have big dreams for Varanasi, but the SP-led state government is putting roadblocks in the implementation of development programmes," Prime Minister Narendra Modi said addressing a rally in Varanasi.'},
        'title': u"Oppn believes in 'kuch ka saath, kuch ka vikas', says PM Modi in Varanasi",
        'title_detail': {   'base': u'http://timesofindia.indiatimes.com/rssfeedstopstories.cms',
                            'language': u'en-US',
                            'type': u'text/plain',
                            'value': u"Oppn believes in 'kuch ka saath, kuch ka vikas', says PM Modi in Varanasi"}},
    {   'guidislink': False,
        'id': u'http://timesofindia.indiatimes.com/elections/assembly-elections/uttar-pradesh/news/pm-modis-roadshow-in-varanasi-bjp-upbeat-campaign-will-fail-says-akhilesh-yadav/articleshow/57479778.cms',
        'link': u'http://timesofindia.indiatimes.com/elections/assembly-elections/uttar-pradesh/news/pm-modis-roadshow-in-varanasi-bjp-upbeat-campaign-will-fail-says-akhilesh-yadav/articleshow/57479778.cms',
        'links': [   {   'href': u'http://timesofindia.indiatimes.com/elections/assembly-elections/uttar-pradesh/news/pm-modis-roadshow-in-varanasi-bjp-upbeat-campaign-will-fail-says-akhilesh-yadav/articleshow/57479778.cms',
                         'rel': u'alternate',
                         'type': u'text/html'}],
        'published': u'Sun, 05 Mar 2017 14:00:53 GMT',
        'published_parsed': time.struct_time(tm_year=2017, tm_mon=3, tm_mday=5, tm_hour=14, tm_min=0, tm_sec=53, tm_wday=6, tm_yday=64, tm_isdst=0),
        'summary': u'Large number of BJP supporters descended on the streets of Varanasi on Sunday as Prime Minister Narendra Modi held a roadshow in the city, the second in as many days. Varanasi goes to polls in the last phase on March 8.',
        'summary_detail': {   'base': u'http://timesofindia.indiatimes.com/rssfeedstopstories.cms',
                              'language': u'en-US',
                              'type': u'text/html',
                              'value': u'Large number of BJP supporters descended on the streets of Varanasi on Sunday as Prime Minister Narendra Modi held a roadshow in the city, the second in as many days. Varanasi goes to polls in the last phase on March 8.'},
        'title': u"PM Modi's roadshow will fail, says Akhilesh",
        'title_detail': {   'base': u'http://timesofindia.indiatimes.com/rssfeedstopstories.cms',
                            'language': u'en-US',
                            'type': u'text/plain',
                            'value': u"PM Modi's roadshow will fail, says Akhilesh"}},
    {   'guidislink': False,
        'id': u'http://timesofindia.indiatimes.com/sports/cricket/australia-in-india/india-v-australia-renshaw-laughs-off-kohlis-toilet-sledge/articleshow/57480238.cms',
        'link': u'http://timesofindia.indiatimes.com/sports/cricket/australia-in-india/india-v-australia-renshaw-laughs-off-kohlis-toilet-sledge/articleshow/57480238.cms',
        'links': [   {   'href': u'http://timesofindia.indiatimes.com/sports/cricket/australia-in-india/india-v-australia-renshaw-laughs-off-kohlis-toilet-sledge/articleshow/57480238.cms',
                         'rel': u'alternate',
                         'type': u'text/html'}],
        'published': u'Sun, 05 Mar 2017 14:22:59 GMT',
        'published_parsed': time.struct_time(tm_year=2017, tm_mon=3, tm_mday=5, tm_hour=14, tm_min=22, tm_sec=59, tm_wday=6, tm_yday=64, tm_isdst=0),
        'summary': u'Young Australian opener Matt Renshaw has belied his age with the way he has batted so far on the tour of India and on Sunday, he was equally impressive in negotiating the constant sledging from Virat Kohli.',
        'summary_detail': {   'base': u'http://timesofindia.indiatimes.com/rssfeedstopstories.cms',
                              'language': u'en-US',
                              'type': u'text/html',
                              'value': u'Young Australian opener Matt Renshaw has belied his age with the way he has batted so far on the tour of India and on Sunday, he was equally impressive in negotiating the constant sledging from Virat Kohli.'},
        'title': u"Renshaw laughs off Kohli's 'toilet' sledge",
        'title_detail': {   'base': u'http://timesofindia.indiatimes.com/rssfeedstopstories.cms',
                            'language': u'en-US',
                            'type': u'text/plain',
                            'value': u"Renshaw laughs off Kohli's 'toilet' sledge"}},
    {   'guidislink': False,
        'id': u'http://timesofindia.indiatimes.com/india/up-governor-writes-to-akhilesh-yadav-why-is-rape-accused-minister-still-in-your-cabinet/articleshow/57477674.cms',
        'link': u'http://timesofindia.indiatimes.com/india/up-governor-writes-to-akhilesh-yadav-why-is-rape-accused-minister-still-in-your-cabinet/articleshow/57477674.cms',
        'links': [   {   'href': u'http://timesofindia.indiatimes.com/india/up-governor-writes-to-akhilesh-yadav-why-is-rape-accused-minister-still-in-your-cabinet/articleshow/57477674.cms',
                         'rel': u'alternate',
                         'type': u'text/html'}],
        'published': u'Sun, 05 Mar 2017 10:45:31 GMT',
        'published_parsed': time.struct_time(tm_year=2017, tm_mon=3, tm_mday=5, tm_hour=10, tm_min=45, tm_sec=31, tm_wday=6, tm_yday=64, tm_isdst=0),
        'summary': u'Uttar Pradesh Governor Ram Naik has written to Akhilesh Yadav asking why has the chief minister retained rape-accused minister Gayatri Prajapati in his cabinet, according to Raj Bhavan sources.',
        'summary_detail': {   'base': u'http://timesofindia.indiatimes.com/rssfeedstopstories.cms',
                              'language': u'en-US',
                              'type': u'text/html',
                              'value': u'Uttar Pradesh Governor Ram Naik has written to Akhilesh Yadav asking why has the chief minister retained rape-accused minister Gayatri Prajapati in his cabinet, according to Raj Bhavan sources.'},
        'title': u'Why rape-accused in cabinet? UP Governor to CM',
        'title_detail': {   'base': u'http://timesofindia.indiatimes.com/rssfeedstopstories.cms',
                            'language': u'en-US',
                            'type': u'text/plain',
                            'value': u'Why rape-accused in cabinet? UP Governor to CM'}},
    {   'guidislink': False,
        'id': u'http://timesofindia.indiatimes.com/world/us/white-house-asks-congress-to-probe-whether-obama-ordered-wiretap/articleshow/57480314.cms',
        'link': u'http://timesofindia.indiatimes.com/world/us/white-house-asks-congress-to-probe-whether-obama-ordered-wiretap/articleshow/57480314.cms',
        'links': [   {   'href': u'http://timesofindia.indiatimes.com/world/us/white-house-asks-congress-to-probe-whether-obama-ordered-wiretap/articleshow/57480314.cms',
                         'rel': u'alternate',
                         'type': u'text/html'}],
        'published': u'Sun, 05 Mar 2017 14:30:04 GMT',
        'published_parsed': time.struct_time(tm_year=2017, tm_mon=3, tm_mday=5, tm_hour=14, tm_min=30, tm_sec=4, tm_wday=6, tm_yday=64, tm_isdst=0),
        'summary': u'The White House on Sunday requested the US Congress examine whether the Obama administration abused its executive "investigative authority" during the 2016 campaign, as part of the ongoing congressional probe into Russia\'s influence on the US presidential election.',
        'summary_detail': {   'base': u'http://timesofindia.indiatimes.com/rssfeedstopstories.cms',
                              'language': u'en-US',
                              'type': u'text/html',
                              'value': u'The White House on Sunday requested the US Congress examine whether the Obama administration abused its executive "investigative authority" during the 2016 campaign, as part of the ongoing congressional probe into Russia\'s influence on the US presidential election.'},
        'title': u'Did Obama order wiretap? Trump seeks probe',
        'title_detail': {   'base': u'http://timesofindia.indiatimes.com/rssfeedstopstories.cms',
                            'language': u'en-US',
                            'type': u'text/plain',
                            'value': u'Did Obama order wiretap? Trump seeks probe'}}][   {   'guidislink': False,
        'id': u'http://timesofindia.indiatimes.com/elections/assembly-elections/uttar-pradesh/news/opposition-believes-in-kuch-ka-saath-kuch-ka-vikas-says-pm-modi-in-varanasi/articleshow/57480913.cms',
        'link': u'http://timesofindia.indiatimes.com/elections/assembly-elections/uttar-pradesh/news/opposition-believes-in-kuch-ka-saath-kuch-ka-vikas-says-pm-modi-in-varanasi/articleshow/57480913.cms',
        'links': [   {   'href': u'http://timesofindia.indiatimes.com/elections/assembly-elections/uttar-pradesh/news/opposition-believes-in-kuch-ka-saath-kuch-ka-vikas-says-pm-modi-in-varanasi/articleshow/57480913.cms',
                         'rel': u'alternate',
                         'type': u'text/html'}],
        'published': u'Sun, 05 Mar 2017 15:22:17 GMT',
        'published_parsed': time.struct_time(tm_year=2017, tm_mon=3, tm_mday=5, tm_hour=15, tm_min=22, tm_sec=17, tm_wday=6, tm_yday=64, tm_isdst=0),
        'summary': u'"I have big dreams for Varanasi, but the SP-led state government is putting roadblocks in the implementation of development programmes," Prime Minister Narendra Modi said addressing a rally in Varanasi.',
        'summary_detail': {   'base': u'http://timesofindia.indiatimes.com/rssfeedstopstories.cms',
                              'language': u'en-US',
                              'type': u'text/html',
                              'value': u'"I have big dreams for Varanasi, but the SP-led state government is putting roadblocks in the implementation of development programmes," Prime Minister Narendra Modi said addressing a rally in Varanasi.'},
        'title': u"Oppn believes in 'kuch ka saath, kuch ka vikas', says PM Modi in Varanasi",
        'title_detail': {   'base': u'http://timesofindia.indiatimes.com/rssfeedstopstories.cms',
                            'language': u'en-US',
                            'type': u'text/plain',
                            'value': u"Oppn believes in 'kuch ka saath, kuch ka vikas', says PM Modi in Varanasi"}},
    {   'guidislink': False,
        'id': u'http://timesofindia.indiatimes.com/elections/assembly-elections/uttar-pradesh/news/pm-modis-roadshow-in-varanasi-bjp-upbeat-campaign-will-fail-says-akhilesh-yadav/articleshow/57479778.cms',
        'link': u'http://timesofindia.indiatimes.com/elections/assembly-elections/uttar-pradesh/news/pm-modis-roadshow-in-varanasi-bjp-upbeat-campaign-will-fail-says-akhilesh-yadav/articleshow/57479778.cms',
        'links': [   {   'href': u'http://timesofindia.indiatimes.com/elections/assembly-elections/uttar-pradesh/news/pm-modis-roadshow-in-varanasi-bjp-upbeat-campaign-will-fail-says-akhilesh-yadav/articleshow/57479778.cms',
                         'rel': u'alternate',
                         'type': u'text/html'}],
        'published': u'Sun, 05 Mar 2017 14:00:53 GMT',
        'published_parsed': time.struct_time(tm_year=2017, tm_mon=3, tm_mday=5, tm_hour=14, tm_min=0, tm_sec=53, tm_wday=6, tm_yday=64, tm_isdst=0),
        'summary': u'Large number of BJP supporters descended on the streets of Varanasi on Sunday as Prime Minister Narendra Modi held a roadshow in the city, the second in as many days. Varanasi goes to polls in the last phase on March 8.',
        'summary_detail': {   'base': u'http://timesofindia.indiatimes.com/rssfeedstopstories.cms',
                              'language': u'en-US',
                              'type': u'text/html',
                              'value': u'Large number of BJP supporters descended on the streets of Varanasi on Sunday as Prime Minister Narendra Modi held a roadshow in the city, the second in as many days. Varanasi goes to polls in the last phase on March 8.'},
        'title': u"PM Modi's roadshow will fail, says Akhilesh",
        'title_detail': {   'base': u'http://timesofindia.indiatimes.com/rssfeedstopstories.cms',
                            'language': u'en-US',
                            'type': u'text/plain',
                            'value': u"PM Modi's roadshow will fail, says Akhilesh"}},
    {   'guidislink': False,
        'id': u'http://timesofindia.indiatimes.com/sports/cricket/australia-in-india/india-v-australia-renshaw-laughs-off-kohlis-toilet-sledge/articleshow/57480238.cms',
        'link': u'http://timesofindia.indiatimes.com/sports/cricket/australia-in-india/india-v-australia-renshaw-laughs-off-kohlis-toilet-sledge/articleshow/57480238.cms',
        'links': [   {   'href': u'http://timesofindia.indiatimes.com/sports/cricket/australia-in-india/india-v-australia-renshaw-laughs-off-kohlis-toilet-sledge/articleshow/57480238.cms',
                         'rel': u'alternate',
                         'type': u'text/html'}],
        'published': u'Sun, 05 Mar 2017 14:22:59 GMT',
        'published_parsed': time.struct_time(tm_year=2017, tm_mon=3, tm_mday=5, tm_hour=14, tm_min=22, tm_sec=59, tm_wday=6, tm_yday=64, tm_isdst=0),
        'summary': u'Young Australian opener Matt Renshaw has belied his age with the way he has batted so far on the tour of India and on Sunday, he was equally impressive in negotiating the constant sledging from Virat Kohli.',
        'summary_detail': {   'base': u'http://timesofindia.indiatimes.com/rssfeedstopstories.cms',
                              'language': u'en-US',
                              'type': u'text/html',
                              'value': u'Young Australian opener Matt Renshaw has belied his age with the way he has batted so far on the tour of India and on Sunday, he was equally impressive in negotiating the constant sledging from Virat Kohli.'},
        'title': u"Renshaw laughs off Kohli's 'toilet' sledge",
        'title_detail': {   'base': u'http://timesofindia.indiatimes.com/rssfeedstopstories.cms',
                            'language': u'en-US',
                            'type': u'text/plain',
                            'value': u"Renshaw laughs off Kohli's 'toilet' sledge"}},
    {   'guidislink': False,
        'id': u'http://timesofindia.indiatimes.com/india/up-governor-writes-to-akhilesh-yadav-why-is-rape-accused-minister-still-in-your-cabinet/articleshow/57477674.cms',
        'link': u'http://timesofindia.indiatimes.com/india/up-governor-writes-to-akhilesh-yadav-why-is-rape-accused-minister-still-in-your-cabinet/articleshow/57477674.cms',
        'links': [   {   'href': u'http://timesofindia.indiatimes.com/india/up-governor-writes-to-akhilesh-yadav-why-is-rape-accused-minister-still-in-your-cabinet/articleshow/57477674.cms',
                         'rel': u'alternate',
                         'type': u'text/html'}],
        'published': u'Sun, 05 Mar 2017 10:45:31 GMT',
        'published_parsed': time.struct_time(tm_year=2017, tm_mon=3, tm_mday=5, tm_hour=10, tm_min=45, tm_sec=31, tm_wday=6, tm_yday=64, tm_isdst=0),
        'summary': u'Uttar Pradesh Governor Ram Naik has written to Akhilesh Yadav asking why has the chief minister retained rape-accused minister Gayatri Prajapati in his cabinet, according to Raj Bhavan sources.',
        'summary_detail': {   'base': u'http://timesofindia.indiatimes.com/rssfeedstopstories.cms',
                              'language': u'en-US',
                              'type': u'text/html',
                              'value': u'Uttar Pradesh Governor Ram Naik has written to Akhilesh Yadav asking why has the chief minister retained rape-accused minister Gayatri Prajapati in his cabinet, according to Raj Bhavan sources.'},
        'title': u'Why rape-accused in cabinet? UP Governor to CM',
        'title_detail': {   'base': u'http://timesofindia.indiatimes.com/rssfeedstopstories.cms',
                            'language': u'en-US',
                            'type': u'text/plain',
                            'value': u'Why rape-accused in cabinet? UP Governor to CM'}},
    {   'guidislink': False,
        'id': u'http://timesofindia.indiatimes.com/world/us/white-house-asks-congress-to-probe-whether-obama-ordered-wiretap/articleshow/57480314.cms',
        'link': u'http://timesofindia.indiatimes.com/world/us/white-house-asks-congress-to-probe-whether-obama-ordered-wiretap/articleshow/57480314.cms',
        'links': [   {   'href': u'http://timesofindia.indiatimes.com/world/us/white-house-asks-congress-to-probe-whether-obama-ordered-wiretap/articleshow/57480314.cms',
                         'rel': u'alternate',
                         'type': u'text/html'}],
        'published': u'Sun, 05 Mar 2017 14:30:04 GMT',
        'published_parsed': time.struct_time(tm_year=2017, tm_mon=3, tm_mday=5, tm_hour=14, tm_min=30, tm_sec=4, tm_wday=6, tm_yday=64, tm_isdst=0),
        'summary': u'The White House on Sunday requested the US Congress examine whether the Obama administration abused its executive "investigative authority" during the 2016 campaign, as part of the ongoing congressional probe into Russia\'s influence on the US presidential election.',
        'summary_detail': {   'base': u'http://timesofindia.indiatimes.com/rssfeedstopstories.cms',
                              'language': u'en-US',
                              'type': u'text/html',
                              'value': u'The White House on Sunday requested the US Congress examine whether the Obama administration abused its executive "investigative authority" during the 2016 campaign, as part of the ongoing congressional probe into Russia\'s influence on the US presidential election.'},
        'title': u'Did Obama order wiretap? Trump seeks probe',
        'title_detail': {   'base': u'http://timesofindia.indiatimes.com/rssfeedstopstories.cms',
                            'language': u'en-US',
                            'type': u'text/plain',
                            'value': u'Did Obama order wiretap? Trump seeks probe'}}][   {   'guidislink': False,
        'id': u'http://timesofindia.indiatimes.com/elections/assembly-elections/uttar-pradesh/news/opposition-believes-in-kuch-ka-saath-kuch-ka-vikas-says-pm-modi-in-varanasi/articleshow/57480913.cms',
        'link': u'http://timesofindia.indiatimes.com/elections/assembly-elections/uttar-pradesh/news/opposition-believes-in-kuch-ka-saath-kuch-ka-vikas-says-pm-modi-in-varanasi/articleshow/57480913.cms',
        'links': [   {   'href': u'http://timesofindia.indiatimes.com/elections/assembly-elections/uttar-pradesh/news/opposition-believes-in-kuch-ka-saath-kuch-ka-vikas-says-pm-modi-in-varanasi/articleshow/57480913.cms',
                         'rel': u'alternate',
                         'type': u'text/html'}],
        'published': u'Sun, 05 Mar 2017 15:22:17 GMT',
        'published_parsed': time.struct_time(tm_year=2017, tm_mon=3, tm_mday=5, tm_hour=15, tm_min=22, tm_sec=17, tm_wday=6, tm_yday=64, tm_isdst=0),
        'summary': u'"I have big dreams for Varanasi, but the SP-led state government is putting roadblocks in the implementation of development programmes," Prime Minister Narendra Modi said addressing a rally in Varanasi.',
        'summary_detail': {   'base': u'http://timesofindia.indiatimes.com/rssfeedstopstories.cms',
                              'language': u'en-US',
                              'type': u'text/html',
                              'value': u'"I have big dreams for Varanasi, but the SP-led state government is putting roadblocks in the implementation of development programmes," Prime Minister Narendra Modi said addressing a rally in Varanasi.'},
        'title': u"Oppn believes in 'kuch ka saath, kuch ka vikas', says PM Modi in Varanasi",
        'title_detail': {   'base': u'http://timesofindia.indiatimes.com/rssfeedstopstories.cms',
                            'language': u'en-US',
                            'type': u'text/plain',
                            'value': u"Oppn believes in 'kuch ka saath, kuch ka vikas', says PM Modi in Varanasi"}},
    {   'guidislink': False,
        'id': u'http://timesofindia.indiatimes.com/elections/assembly-elections/uttar-pradesh/news/pm-modis-roadshow-in-varanasi-bjp-upbeat-campaign-will-fail-says-akhilesh-yadav/articleshow/57479778.cms',
        'link': u'http://timesofindia.indiatimes.com/elections/assembly-elections/uttar-pradesh/news/pm-modis-roadshow-in-varanasi-bjp-upbeat-campaign-will-fail-says-akhilesh-yadav/articleshow/57479778.cms',
        'links': [   {   'href': u'http://timesofindia.indiatimes.com/elections/assembly-elections/uttar-pradesh/news/pm-modis-roadshow-in-varanasi-bjp-upbeat-campaign-will-fail-says-akhilesh-yadav/articleshow/57479778.cms',
                         'rel': u'alternate',
                         'type': u'text/html'}],
        'published': u'Sun, 05 Mar 2017 14:00:53 GMT',
        'published_parsed': time.struct_time(tm_year=2017, tm_mon=3, tm_mday=5, tm_hour=14, tm_min=0, tm_sec=53, tm_wday=6, tm_yday=64, tm_isdst=0),
        'summary': u'Large number of BJP supporters descended on the streets of Varanasi on Sunday as Prime Minister Narendra Modi held a roadshow in the city, the second in as many days. Varanasi goes to polls in the last phase on March 8.',
        'summary_detail': {   'base': u'http://timesofindia.indiatimes.com/rssfeedstopstories.cms',
                              'language': u'en-US',
                              'type': u'text/html',
                              'value': u'Large number of BJP supporters descended on the streets of Varanasi on Sunday as Prime Minister Narendra Modi held a roadshow in the city, the second in as many days. Varanasi goes to polls in the last phase on March 8.'},
        'title': u"PM Modi's roadshow will fail, says Akhilesh",
        'title_detail': {   'base': u'http://timesofindia.indiatimes.com/rssfeedstopstories.cms',
                            'language': u'en-US',
                            'type': u'text/plain',
                            'value': u"PM Modi's roadshow will fail, says Akhilesh"}},
    {   'guidislink': False,
        'id': u'http://timesofindia.indiatimes.com/sports/cricket/australia-in-india/india-v-australia-renshaw-laughs-off-kohlis-toilet-sledge/articleshow/57480238.cms',
        'link': u'http://timesofindia.indiatimes.com/sports/cricket/australia-in-india/india-v-australia-renshaw-laughs-off-kohlis-toilet-sledge/articleshow/57480238.cms',
        'links': [   {   'href': u'http://timesofindia.indiatimes.com/sports/cricket/australia-in-india/india-v-australia-renshaw-laughs-off-kohlis-toilet-sledge/articleshow/57480238.cms',
                         'rel': u'alternate',
                         'type': u'text/html'}],
        'published': u'Sun, 05 Mar 2017 14:22:59 GMT',
        'published_parsed': time.struct_time(tm_year=2017, tm_mon=3, tm_mday=5, tm_hour=14, tm_min=22, tm_sec=59, tm_wday=6, tm_yday=64, tm_isdst=0),
        'summary': u'Young Australian opener Matt Renshaw has belied his age with the way he has batted so far on the tour of India and on Sunday, he was equally impressive in negotiating the constant sledging from Virat Kohli.',
        'summary_detail': {   'base': u'http://timesofindia.indiatimes.com/rssfeedstopstories.cms',
                              'language': u'en-US',
                              'type': u'text/html',
                              'value': u'Young Australian opener Matt Renshaw has belied his age with the way he has batted so far on the tour of India and on Sunday, he was equally impressive in negotiating the constant sledging from Virat Kohli.'},
        'title': u"Renshaw laughs off Kohli's 'toilet' sledge",
        'title_detail': {   'base': u'http://timesofindia.indiatimes.com/rssfeedstopstories.cms',
                            'language': u'en-US',
                            'type': u'text/plain',
                            'value': u"Renshaw laughs off Kohli's 'toilet' sledge"}},
    {   'guidislink': False,
        'id': u'http://timesofindia.indiatimes.com/india/up-governor-writes-to-akhilesh-yadav-why-is-rape-accused-minister-still-in-your-cabinet/articleshow/57477674.cms',
        'link': u'http://timesofindia.indiatimes.com/india/up-governor-writes-to-akhilesh-yadav-why-is-rape-accused-minister-still-in-your-cabinet/articleshow/57477674.cms',
        'links': [   {   'href': u'http://timesofindia.indiatimes.com/india/up-governor-writes-to-akhilesh-yadav-why-is-rape-accused-minister-still-in-your-cabinet/articleshow/57477674.cms',
                         'rel': u'alternate',
                         'type': u'text/html'}],
        'published': u'Sun, 05 Mar 2017 10:45:31 GMT',
        'published_parsed': time.struct_time(tm_year=2017, tm_mon=3, tm_mday=5, tm_hour=10, tm_min=45, tm_sec=31, tm_wday=6, tm_yday=64, tm_isdst=0),
        'summary': u'Uttar Pradesh Governor Ram Naik has written to Akhilesh Yadav asking why has the chief minister retained rape-accused minister Gayatri Prajapati in his cabinet, according to Raj Bhavan sources.',
        'summary_detail': {   'base': u'http://timesofindia.indiatimes.com/rssfeedstopstories.cms',
                              'language': u'en-US',
                              'type': u'text/html',
                              'value': u'Uttar Pradesh Governor Ram Naik has written to Akhilesh Yadav asking why has the chief minister retained rape-accused minister Gayatri Prajapati in his cabinet, according to Raj Bhavan sources.'},
        'title': u'Why rape-accused in cabinet? UP Governor to CM',
        'title_detail': {   'base': u'http://timesofindia.indiatimes.com/rssfeedstopstories.cms',
                            'language': u'en-US',
                            'type': u'text/plain',
                            'value': u'Why rape-accused in cabinet? UP Governor to CM'}},
    {   'guidislink': False,
        'id': u'http://timesofindia.indiatimes.com/world/us/white-house-asks-congress-to-probe-whether-obama-ordered-wiretap/articleshow/57480314.cms',
        'link': u'http://timesofindia.indiatimes.com/world/us/white-house-asks-congress-to-probe-whether-obama-ordered-wiretap/articleshow/57480314.cms',
        'links': [   {   'href': u'http://timesofindia.indiatimes.com/world/us/white-house-asks-congress-to-probe-whether-obama-ordered-wiretap/articleshow/57480314.cms',
                         'rel': u'alternate',
                         'type': u'text/html'}],
        'published': u'Sun, 05 Mar 2017 14:30:04 GMT',
        'published_parsed': time.struct_time(tm_year=2017, tm_mon=3, tm_mday=5, tm_hour=14, tm_min=30, tm_sec=4, tm_wday=6, tm_yday=64, tm_isdst=0),
        'summary': u'The White House on Sunday requested the US Congress examine whether the Obama administration abused its executive "investigative authority" during the 2016 campaign, as part of the ongoing congressional probe into Russia\'s influence on the US presidential election.',
        'summary_detail': {   'base': u'http://timesofindia.indiatimes.com/rssfeedstopstories.cms',
                              'language': u'en-US',
                              'type': u'text/html',
                              'value': u'The White House on Sunday requested the US Congress examine whether the Obama administration abused its executive "investigative authority" during the 2016 campaign, as part of the ongoing congressional probe into Russia\'s influence on the US presidential election.'},
        'title': u'Did Obama order wiretap? Trump seeks probe',
        'title_detail': {   'base': u'http://timesofindia.indiatimes.com/rssfeedstopstories.cms',
                            'language': u'en-US',
                            'type': u'text/plain',
                            'value': u'Did Obama order wiretap? Trump seeks probe'}}]