{   'bozo': 0,
    'encoding': u'UTF-8',
    'entries': [   {   'guidislink': False,
                       'id': u'http://timesofindia.indiatimes.com/elections/assembly-elections/uttar-pradesh/news/opposition-believes-in-kuch-ka-saath-kuch-ka-vikas-says-pm-modi-in-varanasi/articleshow/57480913.cms',
                       'link': u'http://timesofindia.indiatimes.com/elections/assembly-elections/uttar-pradesh/news/opposition-believes-in-kuch-ka-saath-kuch-ka-vikas-says-pm-modi-in-varanasi/articleshow/57480913.cms',
                       'links': [   {   'href': u'http://timesofindia.indiatimes.com/elections/assembly-elections/uttar-pradesh/news/opposition-believes-in-kuch-ka-saath-kuch-ka-vikas-says-pm-modi-in-varanasi/articleshow/57480913.cms',
                                        'rel': u'alternate',
                                        'type': u'text/html'}],
                       'published': u'Sun, 05 Mar 2017 15:22:17 GMT',
                       'published_parsed': time.struct_time(tm_year=2017, tm_mon=3, tm_mday=5, tm_hour=15, tm_min=22, tm_sec=17, tm_wday=6, tm_yday=64, tm_isdst=0),
                       'summary': u'"I have big dreams for Varanasi, but the SP-led state government is putting roadblocks in the implementation of development programmes," Prime Minister Narendra Modi said addressing a rally in Varanasi.',
                       'summary_detail': {   'base': u'http://timesofindia.indiatimes.com/rssfeedstopstories.cms',
                                             'language': u'en-US',
                                             'type': u'text/html',
                                             'value': u'"I have big dreams for Varanasi, but the SP-led state government is putting roadblocks in the implementation of development programmes," Prime Minister Narendra Modi said addressing a rally in Varanasi.'},
                       'title': u"Oppn believes in 'kuch ka saath, kuch ka vikas', says PM Modi in Varanasi",
                       'title_detail': {   'base': u'http://timesofindia.indiatimes.com/rssfeedstopstories.cms',
                                           'language': u'en-US',
                                           'type': u'text/plain',
                                           'value': u"Oppn believes in 'kuch ka saath, kuch ka vikas', says PM Modi in Varanasi"}},
                   {   'guidislink': False,
                       'id': u'http://timesofindia.indiatimes.com/elections/assembly-elections/uttar-pradesh/news/pm-modis-roadshow-in-varanasi-bjp-upbeat-campaign-will-fail-says-akhilesh-yadav/articleshow/57479778.cms',
                       'link': u'http://timesofindia.indiatimes.com/elections/assembly-elections/uttar-pradesh/news/pm-modis-roadshow-in-varanasi-bjp-upbeat-campaign-will-fail-says-akhilesh-yadav/articleshow/57479778.cms',
                       'links': [   {   'href': u'http://timesofindia.indiatimes.com/elections/assembly-elections/uttar-pradesh/news/pm-modis-roadshow-in-varanasi-bjp-upbeat-campaign-will-fail-says-akhilesh-yadav/articleshow/57479778.cms',
                                        'rel': u'alternate',
                                        'type': u'text/html'}],
                       'published': u'Sun, 05 Mar 2017 14:00:53 GMT',
                       'published_parsed': time.struct_time(tm_year=2017, tm_mon=3, tm_mday=5, tm_hour=14, tm_min=0, tm_sec=53, tm_wday=6, tm_yday=64, tm_isdst=0),
                       'summary': u'Large number of BJP supporters descended on the streets of Varanasi on Sunday as Prime Minister Narendra Modi held a roadshow in the city, the second in as many days. Varanasi goes to polls in the last phase on March 8.',
                       'summary_detail': {   'base': u'http://timesofindia.indiatimes.com/rssfeedstopstories.cms',
                                             'language': u'en-US',
                                             'type': u'text/html',
                                             'value': u'Large number of BJP supporters descended on the streets of Varanasi on Sunday as Prime Minister Narendra Modi held a roadshow in the city, the second in as many days. Varanasi goes to polls in the last phase on March 8.'},
                       'title': u"PM Modi's roadshow will fail, says Akhilesh",
                       'title_detail': {   'base': u'http://timesofindia.indiatimes.com/rssfeedstopstories.cms',
                                           'language': u'en-US',
                                           'type': u'text/plain',
                                           'value': u"PM Modi's roadshow will fail, says Akhilesh"}},
                   {   'guidislink': False,
                       'id': u'http://timesofindia.indiatimes.com/elections/live-updates/assembly-elections-2017/liveblog/56645288.cms',
                       'link': u'http://timesofindia.indiatimes.com/elections/live-updates/assembly-elections-2017/liveblog/56645288.cms',
                       'links': [   {   'href': u'http://timesofindia.indiatimes.com/elections/live-updates/assembly-elections-2017/liveblog/56645288.cms',
                                        'rel': u'alternate',
                                        'type': u'text/html'}],
                       'published': u'Sun, 05 Mar 2017 10:49:41 GMT',
                       'published_parsed': time.struct_time(tm_year=2017, tm_mon=3, tm_mday=5, tm_hour=10, tm_min=49, tm_sec=41, tm_wday=6, tm_yday=64, tm_isdst=0),
                       'summary': u'',
                       'summary_detail': {   'base': u'http://timesofindia.indiatimes.com/rssfeedstopstories.cms',
                                             'language': u'en-US',
                                             'type': u'text/html',
                                             'value': u''},
                       'title': u'Live: PM Modi seeks vote for development of UP',
                       'title_detail': {   'base': u'http://timesofindia.indiatimes.com/rssfeedstopstories.cms',
                                           'language': u'en-US',
                                           'type': u'text/plain',
                                           'value': u'Live: PM Modi seeks vote for development of UP'}},
                   {   'guidislink': False,
                       'id': u'http://timesofindia.indiatimes.com/sports/cricket/australia-in-india/india-v-australia-renshaw-laughs-off-kohlis-toilet-sledge/articleshow/57480238.cms',
                       'link': u'http://timesofindia.indiatimes.com/sports/cricket/australia-in-india/india-v-australia-renshaw-laughs-off-kohlis-toilet-sledge/articleshow/57480238.cms',
                       'links': [   {   'href': u'http://timesofindia.indiatimes.com/sports/cricket/australia-in-india/india-v-australia-renshaw-laughs-off-kohlis-toilet-sledge/articleshow/57480238.cms',
                                        'rel': u'alternate',
                                        'type': u'text/html'}],
                       'published': u'Sun, 05 Mar 2017 14:22:59 GMT',
                       'published_parsed': time.struct_time(tm_year=2017, tm_mon=3, tm_mday=5, tm_hour=14, tm_min=22, tm_sec=59, tm_wday=6, tm_yday=64, tm_isdst=0),
                       'summary': u'Young Australian opener Matt Renshaw has belied his age with the way he has batted so far on the tour of India and on Sunday, he was equally impressive in negotiating the constant sledging from Virat Kohli.',
                       'summary_detail': {   'base': u'http://timesofindia.indiatimes.com/rssfeedstopstories.cms',
                                             'language': u'en-US',
                                             'type': u'text/html',
                                             'value': u'Young Australian opener Matt Renshaw has belied his age with the way he has batted so far on the tour of India and on Sunday, he was equally impressive in negotiating the constant sledging from Virat Kohli.'},
                       'title': u"Renshaw laughs off Kohli's 'toilet' sledge",
                       'title_detail': {   'base': u'http://timesofindia.indiatimes.com/rssfeedstopstories.cms',
                                           'language': u'en-US',
                                           'type': u'text/plain',
                                           'value': u"Renshaw laughs off Kohli's 'toilet' sledge"}},
                   {   'guidislink': False,
                       'id': u'http://timesofindia.indiatimes.com/india/up-governor-writes-to-akhilesh-yadav-why-is-rape-accused-minister-still-in-your-cabinet/articleshow/57477674.cms',
                       'link': u'http://timesofindia.indiatimes.com/india/up-governor-writes-to-akhilesh-yadav-why-is-rape-accused-minister-still-in-your-cabinet/articleshow/57477674.cms',
                       'links': [   {   'href': u'http://timesofindia.indiatimes.com/india/up-governor-writes-to-akhilesh-yadav-why-is-rape-accused-minister-still-in-your-cabinet/articleshow/57477674.cms',
                                        'rel': u'alternate',
                                        'type': u'text/html'}],
                       'published': u'Sun, 05 Mar 2017 10:45:31 GMT',
                       'published_parsed': time.struct_time(tm_year=2017, tm_mon=3, tm_mday=5, tm_hour=10, tm_min=45, tm_sec=31, tm_wday=6, tm_yday=64, tm_isdst=0),
                       'summary': u'Uttar Pradesh Governor Ram Naik has written to Akhilesh Yadav asking why has the chief minister retained rape-accused minister Gayatri Prajapati in his cabinet, according to Raj Bhavan sources.',
                       'summary_detail': {   'base': u'http://timesofindia.indiatimes.com/rssfeedstopstories.cms',
                                             'language': u'en-US',
                                             'type': u'text/html',
                                             'value': u'Uttar Pradesh Governor Ram Naik has written to Akhilesh Yadav asking why has the chief minister retained rape-accused minister Gayatri Prajapati in his cabinet, according to Raj Bhavan sources.'},
                       'title': u'Why rape-accused in cabinet? UP Governor to CM',
                       'title_detail': {   'base': u'http://timesofindia.indiatimes.com/rssfeedstopstories.cms',
                                           'language': u'en-US',
                                           'type': u'text/plain',
                                           'value': u'Why rape-accused in cabinet? UP Governor to CM'}}],
    'feed': {   'docs': u'http://timescontent.com/',
                'image': {   'href': u'http://images.photogallery.indiatimes.com/photo.cms?msid=507610',
                             'link': u'http://timesofindia.indiatimes.com',
                             'links': [   {   'href': u'http://timesofindia.indiatimes.com',
                                              'rel': u'alternate',
                                              'type': u'text/html'}],
                             'title': u'Times of India',
                             'title_detail': {   'base': u'http://timesofindia.indiatimes.com/rssfeedstopstories.cms',
                                                 'language': u'en-US',
                                                 'type': u'text/plain',
                                                 'value': u'Times of India'}},
                'language': u'en-gb',
                'link': u'http://timesofindia.indiatimes.com',
                'links': [   {   'href': u'http://timesofindia.indiatimes.com/rssfeedstopstories.cms',
                                 'rel': u'self',
                                 'type': u'application/rss+xml'},
                             {   'href': u'http://timesofindia.indiatimes.com',
                                 'rel': u'alternate',
                                 'type': u'text/html'}],
                'rights': u'Copyright:(C) 2017 Bennett Coleman & Co. Ltd, http://info.indiatimes.com/terms/tou.html',
                'rights_detail': {   'base': u'http://timesofindia.indiatimes.com/rssfeedstopstories.cms',
                                     'language': u'en-US',
                                     'type': u'text/plain',
                                     'value': u'Copyright:(C) 2017 Bennett Coleman & Co. Ltd, http://info.indiatimes.com/terms/tou.html'},
                'subtitle': u'The Times of India: Breaking news, views, reviews, cricket from across India',
                'subtitle_detail': {   'base': u'http://timesofindia.indiatimes.com/rssfeedstopstories.cms',
                                       'language': u'en-US',
                                       'type': u'text/html',
                                       'value': u'The Times of India: Breaking news, views, reviews, cricket from across India'},
                'title': u'Times of India',
                'title_detail': {   'base': u'http://timesofindia.indiatimes.com/rssfeedstopstories.cms',
                                    'language': u'en-US',
                                    'type': u'text/plain',
                                    'value': u'Times of India'}},
    'headers': {   'cache-control': 'public, must-revalidate, max-age=403',
                   'connection': 'close',
                   'content-language': 'en-US',
                   'content-length': '4015',
                   'content-type': 'text/xml;charset=UTF-8',
                   'date': 'Sun, 05 Mar 2017 15:28:19 GMT',
                   'expires': 'Sun, 05 Mar 2017 15:35:02 GMT',
                   'last-modified': 'Sun, 05 Mar 2017 15:26:03 GMT',
                   'server': 'Apache'},
    'href': u'http://timesofindia.indiatimes.com/rssfeedstopstories.cms',
    'namespaces': {   '': u'http://www.w3.org/2005/Atom'},
    'status': 200,
    'updated': 'Sun, 05 Mar 2017 15:26:03 GMT',
    'updated_parsed': time.struct_time(tm_year=2017, tm_mon=3, tm_mday=5, tm_hour=15, tm_min=26, tm_sec=3, tm_wday=6, tm_yday=64, tm_isdst=0),
    'version': u'rss20'}