#file to save data
# fo = open ('')
#Dictionary created from the rss feed afetr parsing:
dict={'bozo': 0,
    'encoding': u'UTF-8',
    'entries': [   {   'guidislink': False,
                       'id': u'http://timesofindia.indiatimes.com/sports/cricket/australia-in-india/india-v-australia-2nd-test-day-1-bangalore/liveblog/57459965.cms',
                       'link': u'http://timesofindia.indiatimes.com/sports/cricket/australia-in-india/india-v-australia-2nd-test-day-1-bangalore/liveblog/57459965.cms',
                       'links': [   {   'href': u'http://timesofindia.indiatimes.com/sports/cricket/australia-in-india/india-v-australia-2nd-test-day-1-bangalore/liveblog/57459965.cms',
                                        'rel': u'alternate',
                                        'type': u'text/html'}],
                       'published': u'Sat, 04 Mar 2017 03:22:14 GMT',
                       # #'published_parsed': time.struct_time(tm_year=2017, tm_mon=3, tm_mday=4, tm_hour=3, tm_min=22, tm_sec=14, tm_wday=5, tm_yday=63, tm_isdst=0),
                       'summary': u'Live Commentary & Live cricket score updates of India Australia 2nd Test Day 1 on Times of India',
                       'summary_detail': {   'base': u'http://timesofindia.indiatimes.com/rssfeedstopstories.cms',
                                             'language': u'en-US',
                                             'type': u'text/html',
                                             'value': u'Live Commentary & Live cricket score updates of India Australia 2nd Test Day 1 on Times of India'},
                       'title': u'2nd Test: Lyon takes 8/50, India all out for 189',
                       'title_detail': {   'base': u'http://timesofindia.indiatimes.com/rssfeedstopstories.cms',
                                           'language': u'en-US',
                                           'type': u'text/plain',
                                           'value': u'2nd Test: Lyon takes 8/50, India all out for 189'}},
                   {   'guidislink': False,
                       'id': u'http://timesofindia.indiatimes.com/nri/us-canada-news/indian-origin-businessman-shot-dead-in-the-us/articleshow/57462656.cms',
                       'link': u'http://timesofindia.indiatimes.com/nri/us-canada-news/indian-origin-businessman-shot-dead-in-the-us/articleshow/57462656.cms',
                       'links': [   {   'href': u'http://timesofindia.indiatimes.com/nri/us-canada-news/indian-origin-businessman-shot-dead-in-the-us/articleshow/57462656.cms',
                                        'rel': u'alternate',
                                        'type': u'text/html'}],
                       'published': u'Sat, 04 Mar 2017 07:06:32 GMT',
                       #'published_parsed': time.struct_time(tm_year=2017, tm_mon=3, tm_mday=4, tm_hour=7, tm_min=6, tm_sec=32, tm_wday=5, tm_yday=63, tm_isdst=0),
                       'summary': u"On Thursday night, Harnish Patel had closed his shop at 11:24 pm and barely ten minutes later he was shot dead outside his house in Lancaster, South Carolina. Local officials in Lancaster, however, did not believe that Patel's killing was a bias crime as investigations are on, The Herald reported.",
                       'summary_detail': {   'base': u'http://timesofindia.indiatimes.com/rssfeedstopstories.cms',
                                             'language': u'en-US',
                                             'type': u'text/html',
                                             'value': u"On Thursday night, Harnish Patel had closed his shop at 11:24 pm and barely ten minutes later he was shot dead outside his house in Lancaster, South Carolina. Local officials in Lancaster, however, did not believe that Patel's killing was a bias crime as investigations are on, The Herald reported."},
                       'title': u'Another Indian-origin man shot dead in US',
                       'title_detail': {   'base': u'http://timesofindia.indiatimes.com/rssfeedstopstories.cms',
                                           'language': u'en-US',
                                           'type': u'text/plain',
                                           'value': u'Another Indian-origin man shot dead in US'}},
                   {   'guidislink': False,
                       'id': u'http://timesofindia.indiatimes.com/india/india-steps-up-efforts-to-tap-waters-of-indus-basin-punjab-and-jk-to-resume-work-on-shahpur-kandi-dam-project/articleshow/57462817.cms',
                       'link': u'http://timesofindia.indiatimes.com/india/india-steps-up-efforts-to-tap-waters-of-indus-basin-punjab-and-jk-to-resume-work-on-shahpur-kandi-dam-project/articleshow/57462817.cms',
                       'links': [   {   'href': u'http://timesofindia.indiatimes.com/india/india-steps-up-efforts-to-tap-waters-of-indus-basin-punjab-and-jk-to-resume-work-on-shahpur-kandi-dam-project/articleshow/57462817.cms',
                                        'rel': u'alternate',
                                        'type': u'text/html'}],
                       'published': u'Sat, 04 Mar 2017 07:21:15 GMT',
                       #'published_parsed': time.struct_time(tm_year=2017, tm_mon=3, tm_mday=4, tm_hour=7, tm_min=21, tm_sec=15, tm_wday=5, tm_yday=63, tm_isdst=0),
                       'summary': u'The 55.5-metre high Shahpur Kandi dam, located in Gurdaspur district of Punjab, will help in providing irrigation facility to 5000 hectares of land in Punjab and 32173 hectares in J&amp;K, besides generation of 206 MW power.',
                       'summary_detail': {   'base': u'http://timesofindia.indiatimes.com/rssfeedstopstories.cms',
                                             'language': u'en-US',
                                             'type': u'text/html',
                                             'value': u'The 55.5-metre high Shahpur Kandi dam, located in Gurdaspur district of Punjab, will help in providing irrigation facility to 5000 hectares of land in Punjab and 32173 hectares in J&amp;K, besides generation of 206 MW power.'},
                       'title': u'India moves to tap waters of Indus basin',
                       'title_detail': {   'base': u'http://timesofindia.indiatimes.com/rssfeedstopstories.cms',
                                           'language': u'en-US',
                                           'type': u'text/plain',
                                           'value': u'India moves to tap waters of Indus basin'}},
                   {   'guidislink': False,
                       'id': u'http://timesofindia.indiatimes.com/world/us/h-1b-visa-reform-to-be-part-of-immigration-package-us-to-india/articleshow/57461794.cms',
                       'link': u'http://timesofindia.indiatimes.com/world/us/h-1b-visa-reform-to-be-part-of-immigration-package-us-to-india/articleshow/57461794.cms',
                       'links': [   {   'href': u'http://timesofindia.indiatimes.com/world/us/h-1b-visa-reform-to-be-part-of-immigration-package-us-to-india/articleshow/57461794.cms',
                                        'rel': u'alternate',
                                        'type': u'text/html'}],
                       'published': u'Sat, 04 Mar 2017 05:57:34 GMT',
                       #'published_parsed': time.struct_time(tm_year=2017, tm_mon=3, tm_mday=4, tm_hour=5, tm_min=57, tm_sec=34, tm_wday=5, tm_yday=63, tm_isdst=0),
                       'summary': u'The US has assured India that the H-1B visas issue was not a priority for it and would be part of the larger immigration reforms package that the new Trump administration is working on.',
                       'summary_detail': {   'base': u'http://timesofindia.indiatimes.com/rssfeedstopstories.cms',
                                             'language': u'en-US',
                                             'type': u'text/html',
                                             'value': u'The US has assured India that the H-1B visas issue was not a priority for it and would be part of the larger immigration reforms package that the new Trump administration is working on.'},
                       'title': u'H-1B visa issue not priority: US to India',
                       'title_detail': {   'base': u'http://timesofindia.indiatimes.com/rssfeedstopstories.cms',
                                           'language': u'en-US',
                                           'type': u'text/plain',
                                           'value': u'H-1B visa issue not priority: US to India'}},
                   {   'guidislink': False,
                       'id': u'http://timesofindia.indiatimes.com/elections/live-updates/assembly-elections-2017/liveblog/56645288.cms',
                       'link': u'http://timesofindia.indiatimes.com/elections/live-updates/assembly-elections-2017/liveblog/56645288.cms',
                       'links': [   {   'href': u'http://timesofindia.indiatimes.com/elections/live-updates/assembly-elections-2017/liveblog/56645288.cms',
                                        'rel': u'alternate',
                                        'type': u'text/html'}],
                       'published': u'Sat, 04 Mar 2017 01:27:03 GMT',
                       #'published_parsed': time.struct_time(tm_year=2017, tm_mon=3, tm_mday=4, tm_hour=1, tm_min=27, tm_sec=3, tm_wday=5, tm_yday=63, tm_isdst=0),
                       'summary': u'',
                       'summary_detail': {   'base': u'http://timesofindia.indiatimes.com/rssfeedstopstories.cms',
                                             'language': u'en-US',
                                             'type': u'text/html',
                                             'value': u''},
                       'title': u'Live: Dimple joins Akhilesh, Rahul in roadshow',
                       'title_detail': {   'base': u'http://timesofindia.indiatimes.com/rssfeedstopstories.cms',
                                           'language': u'en-US',
                                           'type': u'text/plain',
                                           'value': u'Live: Dimple joins Akhilesh, Rahul in roadshow'}}
                                           ],
    'feed': {   'docs': u'http://timescontent.com/',
                'image': {   'href': u'http://images.photogallery.indiatimes.com/photo.cms?msid=507610',
                             'link': u'http://timesofindia.indiatimes.com',
                             'links': [   {   'href': u'http://timesofindia.indiatimes.com',
                                              'rel': u'alternate',
                                              'type': u'text/html'}],
                             'title': u'Times of India',
                             'title_detail': {   'base': u'http://timesofindia.indiatimes.com/rssfeedstopstories.cms',
                                                 'language': u'en-US',
                                                 'type': u'text/plain',
                                                 'value': u'Times of India'}},
                'language': u'en-gb',
                'link': u'http://timesofindia.indiatimes.com',
                'links': [   {   'href': u'http://timesofindia.indiatimes.com/rssfeedstopstories.cms',
                                 'rel': u'self',
                                 'type': u'application/rss+xml'},
                             {   'href': u'http://timesofindia.indiatimes.com',
                                 'rel': u'alternate',
                                 'type': u'text/html'}],
                'rights': u'Copyright:(C) 2017 Bennett Coleman & Co. Ltd, http://info.indiatimes.com/terms/tou.html',
                'rights_detail': {   'base': u'http://timesofindia.indiatimes.com/rssfeedstopstories.cms',
                                     'language': u'en-US',
                                     'type': u'text/plain',
                                     'value': u'Copyright:(C) 2017 Bennett Coleman & Co. Ltd, http://info.indiatimes.com/terms/tou.html'},
                'subtitle': u'The Times of India: Breaking news, views, reviews, cricket from across India',
                'subtitle_detail': {   'base': u'http://timesofindia.indiatimes.com/rssfeedstopstories.cms',
                                       'language': u'en-US',
                                       'type': u'text/html',
                                       'value': u'The Times of India: Breaking news, views, reviews, cricket from across India'},
                'title': u'Times of India',
                'title_detail': {   'base': u'http://timesofindia.indiatimes.com/rssfeedstopstories.cms',
                                    'language': u'en-US',
                                    'type': u'text/plain',
                                    'value': u'Times of India'}},
    'headers': {   'cache-control': 'public, must-revalidate, max-age=366',
                   'connection': 'close',
                   'content-language': 'en-US',
                   'content-length': '3746',
                   'content-type': 'text/xml;charset=UTF-8',
                   'date': 'Sat, 04 Mar 2017 11:24:48 GMT',
                   'expires': 'Sat, 04 Mar 2017 11:30:54 GMT',
                   'last-modified': 'Sat, 04 Mar 2017 11:21:28 GMT',
                   'server': 'Apache'},
    'href': u'http://timesofindia.indiatimes.com/rssfeedstopstories.cms',
    'namespaces': {   '': u'http://www.w3.org/2005/Atom'},
    'status': 200,
    'updated': 'Sat, 04 Mar 2017 11:21:28 GMT',
    #'updated_parsed': time.struct_time(tm_year=2017, tm_mon=3, tm_mday=4, tm_hour=11, tm_min=21, tm_sec=28, tm_wday=5, tm_yday=63, tm_isdst=0),
    'version': u'rss20'}

#running operations over dictionary:
# print (dict['bozo'])
# print (dict['encoding'])
l = []
sampleKeys=dict.keys()
for n in sampleKeys:
  if n=='entries':
    l.append(dict[n])
print("l is here")
print(l)