{   'bozo': 0,
    'encoding': u'UTF-8',
    'entries': [   {   'guidislink': False,
                       'id': u'http://timesofindia.indiatimes.com/india/up-governor-writes-to-akhilesh-yadav-why-is-rape-accused-minister-still-in-your-cabinet/articleshow/57477674.cms',
                       'link': u'http://timesofindia.indiatimes.com/india/up-governor-writes-to-akhilesh-yadav-why-is-rape-accused-minister-still-in-your-cabinet/articleshow/57477674.cms',
                       'links': [   {   'href': u'http://timesofindia.indiatimes.com/india/up-governor-writes-to-akhilesh-yadav-why-is-rape-accused-minister-still-in-your-cabinet/articleshow/57477674.cms',
                                        'rel': u'alternate',
                                        'type': u'text/html'}],
                       'published': u'Sun, 05 Mar 2017 10:45:31 GMT',
                       'published_parsed': time.struct_time(tm_year=2017, tm_mon=3, tm_mday=5, tm_hour=10, tm_min=45, tm_sec=31, tm_wday=6, tm_yday=64, tm_isdst=0),
                       'summary': u'Uttar Pradesh Governor Ram Naik has written to Akhilesh Yadav asking why has the chief minister retained rape-accused minister Gayatri Prajapati in his cabinet, according to Raj Bhavan sources.',
                       'summary_detail': {   'base': u'http://timesofindia.indiatimes.com/rssfeedstopstories.cms',
                                             'language': u'en-US',
                                             'type': u'text/html',
                                             'value': u'Uttar Pradesh Governor Ram Naik has written to Akhilesh Yadav asking why has the chief minister retained rape-accused minister Gayatri Prajapati in his cabinet, according to Raj Bhavan sources.'},
                       'title': u'Why rape-accused minister still in cabinet? UP Governor asks Akhilesh',
                       'title_detail': {   'base': u'http://timesofindia.indiatimes.com/rssfeedstopstories.cms',
                                           'language': u'en-US',
                                           'type': u'text/plain',
                                           'value': u'Why rape-accused minister still in cabinet? UP Governor asks Akhilesh'}},
                   {   'guidislink': False,
                       'id': u'http://timesofindia.indiatimes.com/sports/cricket/australia-in-india/2nd-test-renshaw-marsh-put-australia-in-lead-on-day-two/articleshow/57474957.cms',
                       'link': u'http://timesofindia.indiatimes.com/sports/cricket/australia-in-india/2nd-test-renshaw-marsh-put-australia-in-lead-on-day-two/articleshow/57474957.cms',
                       'links': [   {   'href': u'http://timesofindia.indiatimes.com/sports/cricket/australia-in-india/2nd-test-renshaw-marsh-put-australia-in-lead-on-day-two/articleshow/57474957.cms',
                                        'rel': u'alternate',
                                        'type': u'text/html'}],
                       'published': u'Sun, 05 Mar 2017 06:21:42 GMT',
                       'published_parsed': time.struct_time(tm_year=2017, tm_mon=3, tm_mday=5, tm_hour=6, tm_min=21, tm_sec=42, tm_wday=6, tm_yday=64, tm_isdst=0),
                       'summary': u'Australia managed to stay ahead mainly riding on Matt Renshaw and Shaun Marsh supreme effort in the middle, battling a difficult pitch and a disciplined Indian bowling attack on day two. Australia finished the day on 237 for six, with a lead of 48 runs.',
                       'summary_detail': {   'base': u'http://timesofindia.indiatimes.com/rssfeedstopstories.cms',
                                             'language': u'en-US',
                                             'type': u'text/html',
                                             'value': u'Australia managed to stay ahead mainly riding on Matt Renshaw and Shaun Marsh supreme effort in the middle, battling a difficult pitch and a disciplined Indian bowling attack on day two. Australia finished the day on 237 for six, with a lead of 48 runs.'},
                       'title': u'2nd Test: Renshaw, Marsh put Australia in lead',
                       'title_detail': {   'base': u'http://timesofindia.indiatimes.com/rssfeedstopstories.cms',
                                           'language': u'en-US',
                                           'type': u'text/plain',
                                           'value': u'2nd Test: Renshaw, Marsh put Australia in lead'}},
                   {   'guidislink': False,
                       'id': u'http://timesofindia.indiatimes.com/world/us/donald-trump-expected-to-sign-revised-travel-ban-tomorrow-us-media/articleshow/57476924.cms',
                       'link': u'http://timesofindia.indiatimes.com/world/us/donald-trump-expected-to-sign-revised-travel-ban-tomorrow-us-media/articleshow/57476924.cms',
                       'links': [   {   'href': u'http://timesofindia.indiatimes.com/world/us/donald-trump-expected-to-sign-revised-travel-ban-tomorrow-us-media/articleshow/57476924.cms',
                                        'rel': u'alternate',
                                        'type': u'text/html'}],
                       'published': u'Sun, 05 Mar 2017 09:31:24 GMT',
                       'published_parsed': time.struct_time(tm_year=2017, tm_mon=3, tm_mday=5, tm_hour=9, tm_min=31, tm_sec=24, tm_wday=6, tm_yday=64, tm_isdst=0),
                       'summary': u'The order, which temporarily barred people from seven Muslim-majority countries from traveling to the United States for 90 days, as well as all refugees for 120 days and Syrian refugees permanently \u2014 triggered worldwide outrage..',
                       'summary_detail': {   'base': u'http://timesofindia.indiatimes.com/rssfeedstopstories.cms',
                                             'language': u'en-US',
                                             'type': u'text/html',
                                             'value': u'The order, which temporarily barred people from seven Muslim-majority countries from traveling to the United States for 90 days, as well as all refugees for 120 days and Syrian refugees permanently \u2014 triggered worldwide outrage..'},
                       'title': u'Trump may sign new travel ban tomorrow: Report',
                       'title_detail': {   'base': u'http://timesofindia.indiatimes.com/rssfeedstopstories.cms',
                                           'language': u'en-US',
                                           'type': u'text/plain',
                                           'value': u'Trump may sign new travel ban tomorrow: Report'}},
                   {   'guidislink': False,
                       'id': u'http://timesofindia.indiatimes.com/business/india-business/sbi-to-charge-penalty-for-breach-of-minimum-balance-from-april/articleshow/57478244.cms',
                       'link': u'http://timesofindia.indiatimes.com/business/india-business/sbi-to-charge-penalty-for-breach-of-minimum-balance-from-april/articleshow/57478244.cms',
                       'links': [   {   'href': u'http://timesofindia.indiatimes.com/business/india-business/sbi-to-charge-penalty-for-breach-of-minimum-balance-from-april/articleshow/57478244.cms',
                                        'rel': u'alternate',
                                        'type': u'text/html'}],
                       'published': u'Sun, 05 Mar 2017 11:23:37 GMT',
                       'published_parsed': time.struct_time(tm_year=2017, tm_mon=3, tm_mday=5, tm_hour=11, tm_min=23, tm_sec=37, tm_wday=6, tm_yday=64, tm_isdst=0),
                       'summary': u'',
                       'summary_detail': {   'base': u'http://timesofindia.indiatimes.com/rssfeedstopstories.cms',
                                             'language': u'en-US',
                                             'type': u'text/html',
                                             'value': u''},
                       'title': u'SBI to charge for breach of min balance from April',
                       'title_detail': {   'base': u'http://timesofindia.indiatimes.com/rssfeedstopstories.cms',
                                           'language': u'en-US',
                                           'type': u'text/plain',
                                           'value': u'SBI to charge for breach of min balance from April'}},
                   {   'guidislink': False,
                       'id': u'http://timesofindia.indiatimes.com/elections/live-updates/assembly-elections-2017/liveblog/56645288.cms',
                       'link': u'http://timesofindia.indiatimes.com/elections/live-updates/assembly-elections-2017/liveblog/56645288.cms',
                       'links': [   {   'href': u'http://timesofindia.indiatimes.com/elections/live-updates/assembly-elections-2017/liveblog/56645288.cms',
                                        'rel': u'alternate',
                                        'type': u'text/html'}],
                       'published': u'Sun, 05 Mar 2017 10:49:41 GMT',
                       'published_parsed': time.struct_time(tm_year=2017, tm_mon=3, tm_mday=5, tm_hour=10, tm_min=49, tm_sec=41, tm_wday=6, tm_yday=64, tm_isdst=0),
                       'summary': u'',
                       'summary_detail': {   'base': u'http://timesofindia.indiatimes.com/rssfeedstopstories.cms',
                                             'language': u'en-US',
                                             'type': u'text/html',
                                             'value': u''},
                       'title': u'Live: PM Modi holds roadshow in Varanasi',
                       'title_detail': {   'base': u'http://timesofindia.indiatimes.com/rssfeedstopstories.cms',
                                           'language': u'en-US',
                                           'type': u'text/plain',
                                           'value': u'Live: PM Modi holds roadshow in Varanasi'}}],
    'feed': {   'docs': u'http://timescontent.com/',
                'image': {   'href': u'http://images.photogallery.indiatimes.com/photo.cms?msid=507610',
                             'link': u'http://timesofindia.indiatimes.com',
                             'links': [   {   'href': u'http://timesofindia.indiatimes.com',
                                              'rel': u'alternate',
                                              'type': u'text/html'}],
                             'title': u'Times of India',
                             'title_detail': {   'base': u'http://timesofindia.indiatimes.com/rssfeedstopstories.cms',
                                                 'language': u'en-US',
                                                 'type': u'text/plain',
                                                 'value': u'Times of India'}},
                'language': u'en-gb',
                'link': u'http://timesofindia.indiatimes.com',
                'links': [   {   'href': u'http://timesofindia.indiatimes.com/rssfeedstopstories.cms',
                                 'rel': u'self',
                                 'type': u'application/rss+xml'},
                             {   'href': u'http://timesofindia.indiatimes.com',
                                 'rel': u'alternate',
                                 'type': u'text/html'}],
                'rights': u'Copyright:(C) 2017 Bennett Coleman & Co. Ltd, http://info.indiatimes.com/terms/tou.html',
                'rights_detail': {   'base': u'http://timesofindia.indiatimes.com/rssfeedstopstories.cms',
                                     'language': u'en-US',
                                     'type': u'text/plain',
                                     'value': u'Copyright:(C) 2017 Bennett Coleman & Co. Ltd, http://info.indiatimes.com/terms/tou.html'},
                'subtitle': u'The Times of India: Breaking news, views, reviews, cricket from across India',
                'subtitle_detail': {   'base': u'http://timesofindia.indiatimes.com/rssfeedstopstories.cms',
                                       'language': u'en-US',
                                       'type': u'text/html',
                                       'value': u'The Times of India: Breaking news, views, reviews, cricket from across India'},
                'title': u'Times of India',
                'title_detail': {   'base': u'http://timesofindia.indiatimes.com/rssfeedstopstories.cms',
                                    'language': u'en-US',
                                    'type': u'text/plain',
                                    'value': u'Times of India'}},
    'headers': {   'cache-control': 'public, must-revalidate, max-age=273',
                   'connection': 'close',
                   'content-language': 'en-US',
                   'content-length': '3678',
                   'content-type': 'text/xml;charset=UTF-8',
                   'date': 'Sun, 05 Mar 2017 11:46:46 GMT',
                   'expires': 'Sun, 05 Mar 2017 11:51:19 GMT',
                   'last-modified': 'Sun, 05 Mar 2017 11:41:56 GMT',
                   'server': 'Apache'},
    'href': u'http://timesofindia.indiatimes.com/rssfeedstopstories.cms',
    'namespaces': {   '': u'http://www.w3.org/2005/Atom'},
    'status': 200,
    'updated': 'Sun, 05 Mar 2017 11:41:56 GMT',
    'updated_parsed': time.struct_time(tm_year=2017, tm_mon=3, tm_mday=5, tm_hour=11, tm_min=41, tm_sec=56, tm_wday=6, tm_yday=64, tm_isdst=0),
    'version': u'rss20'}